package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.NUnitStep
import jetbrains.buildServer.configs.kotlin.buildSteps.dotnetBuild
import jetbrains.buildServer.configs.kotlin.buildSteps.nunit
import jetbrains.buildServer.configs.kotlin.buildSteps.nunitConsole
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'NUnitConsoleRunnerDeprecatedNUnitRunner1dll'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("NUnitConsoleRunnerDeprecatedNUnitRunner1dll")) {
    expectSteps {
        dotnetBuild {
            name = "Build Project"
            id = "Build_Project"
            projects = "NUnitTests.sln"
            param("dotNetCoverage.dotCover.home.path", "%teamcity.tool.JetBrains.dotCover.CommandLineTools.DEFAULT%")
        }
        nunitConsole {
            name = "nUnit tests"
            id = "nUnit_tests"
            nunitPath = "%teamcity.tool.NUnit.Console.3.17.0%"
            includeTests = """NUnitTests\bin\Debug\net8.0\NUnitTests.dll"""
            param("dotNetCoverage.dotCover.home.path", "%teamcity.tool.JetBrains.dotCover.CommandLineTools.DEFAULT%")
        }
        nunit {
            name = "NUnit: deprecated, dll"
            id = "NUnit_deprecated_dll"
            nunitVersion = NUnitStep.NUnitVersion.NUnit_2_6_4
            runtimeVersion = NUnitStep.RuntimeVersion.v4_0
            includeTests = """NUnitTests\bin\Debug\net8.0\NUnitTests.dll"""
            runProcessPerAssembly = true
        }
    }
    steps {
        update<NUnitStep>(2) {
            clearConditions()
            platform = NUnitStep.Platform.x64
            runProcessPerAssembly = false
        }
    }
}
