package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildFeatures.perfmon
import jetbrains.buildServer.configs.kotlin.buildSteps.dotnetBuild
import jetbrains.buildServer.configs.kotlin.buildSteps.nunitConsole
import jetbrains.buildServer.configs.kotlin.triggers.vcs
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'NUnitConsoleRunner1dllDotCover'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("NUnitConsoleRunner1dllDotCover")
    name = "✔️ NUnit Console Runner: 1 dll + dotCover"

    vcs {
        root(DslContext.settingsRoot)
    }

    steps {
        dotnetBuild {
            name = "Build Project"
            id = "Build_Project"
            projects = "NUnitTests.sln"
            param("dotNetCoverage.dotCover.home.path", "%teamcity.tool.JetBrains.dotCover.CommandLineTools.DEFAULT%")
        }
        nunitConsole {
            name = "nUnit tests"
            id = "nUnit_tests"
            nunitPath = "%teamcity.tool.NUnit.Console.3.17.0%"
            includeTests = """NUnitTests\bin\Debug\net8.0\NUnitTests.dll"""
            useProjectFile = true
            coverage = dotcover {
                toolPath = "%teamcity.tool.JetBrains.dotCover.CommandLineTools.DEFAULT%"
            }
        }
    }

    triggers {
        vcs {
        }
    }

    failureConditions {
        testFailure = false
        nonZeroExitCode = false
    }

    features {
        perfmon {
        }
    }
}))

